name: spa_server
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.7.0
  shelf_router: ^1.1.1
  shelf_static: ^1.1.0
  crypto: ^3.0.0
  mongo_dart: ^0.7.1
  dart_jsonwebtoken: ^2.3.2
  envify: ^2.0.2
  redis: ^2.0.0
  uuid: ^3.0.4


dev_dependencies:
  http: ^0.13.3
  pedantic: ^1.11.1
  test: ^1.17.12
  envify_generator: ^2.0.2
  build_runner: ^2.1.2
